### ISSUE TITLE
6.3

### ISSUE THREAD

**Issue by drejjmit** [Critical-Impact/InventoryTools#173]
Hi!
Are there any plans for a 6.3 release?

```2023-01-11 17:26:26.835 +01:00 [ERR] [LOCALPLUGIN] Error while loading Allagan Tools
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MissingMethodException: Method not found: 'Int32 (FFXIVClientStructs.FFXIV.Client.Game.InventoryManager*, FFXIVClientStructs.FFXIV.Client.Game.InventoryType, UInt32, FFXIVClientStructs.FFXIV.Client.Game.InventoryType, UInt32, Byte) FFXIVClientStructs.FFXIV.Client.Game.InventoryManager.get_fpMoveItemSlot()'.
   at CriticalCommonLib.Services.GameInterface.Initialise(SigScanner targetModuleScanner)
   at InventoryTools.PluginService.Initialise(DalamudPluginInterface pluginInterface) in /work/repo/InventoryTools/PluginService.cs:line 49
   at InventoryTools.InventoryToolsPlugin..ctor(DalamudPluginInterface pluginInterface) in /work/repo/InventoryTools/InventoryToolsPlugin.cs:line 17
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 455```

**Comment by drejjmit** [comment]
Thank you for the update! 
Had no idea how much i relied on your plugin before it was gone xD
