### ISSUE TITLE
'Allagan Tools' failed to install

### ISSUE THREAD

**Issue by marcus-pzj** [Critical-Impact/InventoryTools#284]
**Describe the bug**
Allagan Tools failed to install on Dalamud Plugin Installer. A quick look at the logs surfaces the following error with Inventory Tools: 
`[ERR] [InventoryTools] Plugin startup faulted.
System.AggregateException: One or more errors occurred. (Index must be within the bounds of the List. (Parameter 'index'))
`

**To Reproduce**
1. Go to 'Plugin Installer'
2. Install 'Allagan Tools'
3. 'Allagan Tools' failed to install
4. Plugin failed to load, and needs to be scheduled for deletion upon next restart.

**Error Log**
```2024-11-01 10:52:30.287 +08:00 [INF] [PROFILE] Removing plugin InventoryTools("360589b8-56c7-4edd-ba2a-e9cd9cd3bef9") from profile "00000000-0000-0000-0000-000000000000"
2024-11-01 10:52:30.387 +08:00 [INF] [PLUGINM] Installed plugin Allagan Tools (testing=False)
2024-11-01 10:52:30.387 +08:00 [INF] [PLUGINM] Loading plugin Allagan Tools
2024-11-01 10:52:30.387 +08:00 [WRN] [PROFMAN] '"e5e672f8-e048-4be6-9287-851f9f799a4f"'('InventoryTools') was not in any profile, adding to default with true
2024-11-01 10:52:30.388 +08:00 [INF] [PROFILE] Adding plugin InventoryTools("e5e672f8-e048-4be6-9287-851f9f799a4f") to profile "00000000-0000-0000-0000-000000000000" with state true
2024-11-01 10:52:30.388 +08:00 [INF] [PLUGINM] InventoryTools defaultState: true wantedByAnyProfile: true loadPlugin: true
2024-11-01 10:52:30.389 +08:00 [INF] [LOCALPLUGIN] Loading InventoryTools.dll
2024-11-01 10:52:33.299 +08:00 [INF] [InventoryTools] [Migrat...ervice]{2} Migrating to version 18: 
2024-11-01 10:52:33.304 +08:00 [ERR] [InventoryTools] [           Host]{4} Hosting failed to start: Index must be within the bounds of the List. (Parameter 'index')   at InventoryTools.Services.MigrationManagerService.AddStain2ToInventories() in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 342
   at InventoryTools.Services.MigrationManagerService.RunMigrations() in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 298
   at InventoryTools.Services.MigrationManagerService.StartAsync(CancellationToken cancellationToken) in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 356
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)

2024-11-01 10:52:33.305 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMS0wMVQxMDo1MjozMy4zMDUwODI2KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IE9uZSBvciBtb3JlIGVycm9ycyBvY2N1cnJlZC4gKEluZGV4IG11c3QgYmUgd2l0aGluIHRoZSBib3VuZHMgb2YgdGhlIExpc3QuIChQYXJhbWV0ZXIgJ2luZGV4JykpXHJcbiAtLS0+IFN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IEluZGV4IG11c3QgYmUgd2l0aGluIHRoZSBib3VuZHMgb2YgdGhlIExpc3QuIChQYXJhbWV0ZXIgJ2luZGV4JylcclxuICAgYXQgSW52ZW50b3J5VG9vbHMuU2VydmljZXMuTWlncmF0aW9uTWFuYWdlclNlcnZpY2UuQWRkU3RhaW4yVG9JbnZlbnRvcmllcygpIGluIC93b3JrL3JlcG8vSW52ZW50b3J5VG9vbHMvU2VydmljZXMvTWlncmF0aW9uTWFuYWdlclNlcnZpY2UuY3M6bGluZSAzNDJcclxuICAgYXQgSW52ZW50b3J5VG9vbHMuU2VydmljZXMuTWlncmF0aW9uTWFuYWdlclNlcnZpY2UuUnVuTWlncmF0aW9ucygpIGluIC93b3JrL3JlcG8vSW52ZW50b3J5VG9vbHMvU2VydmljZXMvTWlncmF0aW9uTWFuYWdlclNlcnZpY2UuY3M6bGluZSAyOThcclxuICAgYXQgSW52ZW50b3J5VG9vbHMuU2VydmljZXMuTWlncmF0aW9uTWFuYWdlclNlcnZpY2UuU3RhcnRBc3luYyhDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbikgaW4gL3dvcmsvcmVwby9JbnZlbnRvcnlUb29scy9TZXJ2aWNlcy9NaWdyYXRpb25NYW5hZ2VyU2VydmljZS5jczpsaW5lIDM1NlxyXG4gICBhdCBNaWNyb3NvZnQuRXh0ZW5zaW9ucy5Ib3N0aW5nLkludGVybmFsLkhvc3QuPFN0YXJ0QXN5bmM+Yl9fMTVfMShJSG9zdGVkU2VydmljZSBzZXJ2aWNlLCBDYW5jZWxsYXRpb25Ub2tlbiB0b2tlbilcclxuICAgYXQgTWljcm9zb2Z0LkV4dGVuc2lvbnMuSG9zdGluZy5JbnRlcm5hbC5Ib3N0LkZvcmVhY2hTZXJ2aWNlW1RdKElFbnVtZXJhYmxlYDEgc2VydmljZXMsIENhbmNlbGxhdGlvblRva2VuIHRva2VuLCBCb29sZWFuIGNvbmN1cnJlbnQsIEJvb2xlYW4gYWJvcnRPbkZpcnN0RXhjZXB0aW9uLCBMaXN0YDEgZXhjZXB0aW9ucywgRnVuY2AzIG9wZXJhdGlvbilcclxuICAgYXQgTWljcm9zb2Z0LkV4dGVuc2lvbnMuSG9zdGluZy5JbnRlcm5hbC5Ib3N0LjxTdGFydEFzeW5jPmdfX0xvZ0FuZFJldGhyb3d8MTVfMyg8PmNfX0Rpc3BsYXlDbGFzczE1XzAmKVxyXG4gICBhdCBNaWNyb3NvZnQuRXh0ZW5zaW9ucy5Ib3N0aW5nLkludGVybmFsLkhvc3QuU3RhcnRBc3luYyhDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgLS0tIEVuZCBvZiBpbm5lciBleGNlcHRpb24gc3RhY2sgdHJhY2UgLS0tIiwiQ29udGV4dCI6IltJbnZlbnRvcnlUb29sc10gUGx1Z2luIHN0YXJ0dXAgZmF1bHRlZC4ifQ==
2024-11-01 10:52:33.304 +08:00 [ERR] [InventoryTools] Plugin startup faulted.
System.AggregateException: One or more errors occurred. (Index must be within the bounds of the List. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at InventoryTools.Services.MigrationManagerService.AddStain2ToInventories() in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 342
   at InventoryTools.Services.MigrationManagerService.RunMigrations() in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 298
   at InventoryTools.Services.MigrationManagerService.StartAsync(CancellationToken cancellationToken) in /work/repo/InventoryTools/Services/MigrationManagerService.cs:line 356
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Dalamud Information:**
Do you have testing enabled?
Yes, but I have also tried disabling testing, but it reproduces the same error.

**Comment by Critical-Impact** [comment]
Can you please post your inventories.csv file, it's available in %AppData%\XIVLauncher\pluginConfigs\InventoryTools
The only reason this would happen is if your inventories file was corrupt or if it was migrated and you restored an old version of your main configuration file. If you want to fix this, I can take a look at the file or if you delete inventories.csv it'll be recreated the next time you load the plugin

**Comment by marcus-pzj** [comment]
Hi, thanks for the prompt response. As you suggested, I have resolved this issue by deleting inventories.csv.  🫰 
I will proceed to close this issue.
